services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Kevin@123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./sqlserver:/docker-entrypoint-initdb
    networks:
      - compulnyx-network
    command: |
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &
      
        echo 'Waiting for SQL Server to start...'
        for i in {1..30}; do
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Kevin@123' -Q 'SELECT 1' && break
          sleep 2
        done
      
        echo 'Creating database compulnyx...'
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Kevin@123' -i /docker-entrypoint-initdb/init.sql
      
        wait
      "


  business-logic:
    image: business-service:latest
    container_name: business-logic
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=compulnyx;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Kevin@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.microsoft.sqlserver.jdbc.SQLServerDriver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.SQLServerDialect
      SPRING_APPLICATION_NAME: Business-Service
      SERVER_PORT: 8000
    depends_on:
      - sqlserver
    networks:
      - compulnyx-network

networks:
  compulnyx-network:

volumes:
  sqlserver-data:
